
#Typically do   make update ; make tests
# (make can be made to trigger  update, but imay not laway be wanted and
#  it is hard to  get TESTS set propoerly if update has not been run. )

include    Makevars.in
include ../Makevars

#tests: $(UPDATE) $(TESTS:%=%out)
tests:  $(TESTS:%=%out)

include ../Makerules


