# This default Makefile gets copied to any subdirectories that do not have
#  a Makefile. It should work in most cases, but specilized situations can
#  be handled by a customized Makefile in a subdirectory.

include ../../Makevars
include ../../Makevars.site

-include Makefile.depends

TESTS=${wildcard *.[rR] }

tests: testsite testfresh

.NOTPARALLEL: $(TESTS:%=%out) $(TESTS:%=%outfresh) # only for db conflicts

testsite: $(TESTS:%=%out)

# grep -v gets rid of lines that may change 
$(TESTS:%=%out):%out: %   $(SITE:%=$(RPATH)/site-library/%)
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS=$(RPATH)/library 
	    R_LIBS_SITE=$(RPATH)/site-library  $(RB)  $< $@.fail
	@if [ -f $@.save ]; then  \
	  grep -v "trying URL" $@.save | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\." >$@.save.tmp ; \
	  grep -v "trying URL" $@.fail | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\." >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@


testfresh: $(TESTS:%=%outfresh)


$(TESTS:%=%outfresh):%outfresh: %   $(FRESH:%=$(RPATH)/site-library-fresh/%) 
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS_SITE=$(RPATH)/site-library-fresh
	    R_LIBS=$(RPATH)/library  $(RB)  $< $@.fail
	@if [ -f $(subst fresh,,$@.save) ]; then  \
	  grep -v "trying URL" $(subst fresh,,$@.save) | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\.">$@.save.tmp ; \
	  grep -v "trying URL" $@.fail | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\." >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@

testdevel: $(TESTS:%=%outdevel)

$(TESTS:%=%outdevel):%outdevel: %   $(DEVEL:%=$(RPATH)/site-library-devel/%) \
                   $(FRESHnotDEVEL:%=$(RPATH)/site-library-fresh-notdevel/%)  
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS_SITE=$(RPATH)/site-library-devel:$(RPATH)/site-library-fresh-notdevel \
	    R_LIBS=$(RPATH)/library   $(RB)  $< $@.fail
	@if [ -f $(subst devel,,$@.save) ]; then  \
	  grep -v "trying URL" $(subst devel,,$@.save) | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\.">$@.save.tmp ; \
	  grep -v "trying URL" $@.fail | \
	  grep -v "downloaded" | grep -v "\.\.\.\.\." >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@

clean:
	$(RM) *.Rout *.Routfresh *.Routdevel Rplots.pdf *.fail
	$(RM) *.Rout.fail.tmp *.Routfresh.fail.tmp *.Routdevel.fail.tmp
	$(RM) *.Rout.save.tmp *.Routfresh.save.tmp *.Routdevel.save.tmp
