# This default Makefile gets copied to any subdirectories that do not have
#  a Makefile. It should work in most cases, but specilized situations can
#  be handled by a customized Makefile in a subdirectory.

include ../../Makevars
include ../../Makevars.site

-include Makefile.depends

TESTS=${wildcard *.[rR] }

tests: testsite testfresh

.NOTPARALLEL: $(TESTS:%=%out) $(TESTS:%=%outfresh) # only for db conflicts

testsite: $(TESTS:%=%out)

# grep -v gets rid of lines that may change 
define RdiffPlus
  grep -v "trying URL" | grep -v "downloaded" |  grep -v "\.\.\.\.\." | \
  grep -v "closing unused connection" 
endef

$(TESTS:%=%out):%out: %   $(DEPENDS_PKGS:%=$(RPATH)/site-library/%)
	@$(RM) $@ 
	@echo making $@ ...
	@R_LIBS=$(RPATH)/library \
	    R_LIBS_SITE=$(RPATH)/site-library  $(RB)  $< $@.fail
	@if [ -f $@.save ]; then  \
	  cat $@.save | $(RdiffPlus) >$@.save.tmp ; \
	  cat $@.fail | $(RdiffPlus) >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@echo completed $@ 
	@mv $@.fail $@


testfresh: $(TESTS:%=%outfresh)


$(TESTS:%=%outfresh):%outfresh: % $(DEPENDS_PKGS:%=$(RPATH)/site-library-fresh/%) 
	@$(RM) $@ 
	@echo making $@ ...
	@R_LIBS_SITE=$(RPATH)/site-library-fresh \
	    R_LIBS=$(RPATH)/library  $(RB)  $< $@.fail
	@if [ -f $(subst fresh,,$@.save) ]; then  \
	  cat $(subst fresh,,$@.save) | $(RdiffPlus) >$@.save.tmp ; \
	  cat   $@.fail               | $(RdiffPlus) >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@echo completed $@ 
	@mv $@.fail $@

clean:
	$(RM) *.Rout *.Routfresh *.Routdevel Rplots.pdf *.fail
	$(RM) *.Rout.fail.tmp *.Routfresh.fail.tmp 
	$(RM) *.Rout.save.tmp *.Routfresh.save.tmp 
