# This default Makefile gets copied to any subdirectories that do not have
#  a Makefile. It should work in most cases, but specilized situations can
#  be handled by a customized Makefile in a subdirectory.

include ../../Makevars
include ../../Makevars.site

-include Makefile.depends

TESTS=${wildcard *.[rR] }

tests: testsite testfresh

.NOTPARALLEL: $(TESTS:%=%out) $(TESTS:%=%outfresh) # only for db conflicts

testsite: $(TESTS:%=%out)
define RdiffPlus
  grep -v "trying URL" | grep -v "downloaded" |  grep -v "\.\.\.\.\." | \
  grep -v "closing unused connection" 
endef

# grep -v gets rid of lines that may change 
$(TESTS:%=%out):%out: %   $(SITE_PKGS:%=$(RPATH)/site-library/%)
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS=$(RPATH)/library \
	    R_LIBS_SITE=$(RPATH)/site-library  $(RB)  $< $@.fail
	@if [ -f $@.save ]; then  \
	  cat $@.save | $(RdiffPlus) >$@.save.tmp ; \
	  cat $@.fail | $(RdiffPlus) >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@


testfresh: $(TESTS:%=%outfresh)


$(TESTS:%=%outfresh):%outfresh: %   $(FRESH_PKGS:%=$(RPATH)/site-library-fresh/%) 
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS_SITE=$(RPATH)/site-library-fresh \
	    R_LIBS=$(RPATH)/library  $(RB)  $< $@.fail
	@if [ -f $(subst fresh,,$@.save) ]; then  \
	  cat $(subst fresh,,$@.save) | $(RdiffPlus) >$@.save.tmp ; \
	  cat   $@.fail               | $(RdiffPlus) >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@

testdevel: $(TESTS:%=%outdevel)

$(TESTS:%=%outdevel):%outdevel: %   $(DEVEL_PKGS:%=$(RPATH)/site-library-devel/%) \
                   $(FRESHnotDEVEL:%=$(RPATH)/site-library-fresh-notdevel/%)  
	@$(RM) $@ 
	@echo making $@ ...
	R_LIBS_SITE=$(RPATH)/site-library-devel:$(RPATH)/site-library-fresh-notdevel \
	    R_LIBS=$(RPATH)/library   $(RB)  $< $@.fail
	@if [ -f $(subst devel,,$@.save) ]; then  \
	  cat $(subst devel,,$@.save) | $(RdiffPlus) >$@.save.tmp ; \
	  cat     $@.fail             | $(RdiffPlus) >$@.fail.tmp ; \
	  $(Rdiff) $@.save.tmp  $@.fail.tmp 1 ; fi
	@$(RM) $@.save.tmp $@.fail.tmp 
	@mv $@.fail $@

clean:
	$(RM) *.Rout *.Routfresh *.Routdevel Rplots.pdf *.fail
	$(RM) *.Rout.fail.tmp *.Routfresh.fail.tmp *.Routdevel.fail.tmp
	$(RM) *.Rout.save.tmp *.Routfresh.save.tmp *.Routdevel.save.tmp
