# these set dependencies in the default Makefile:
# $(SITE_PKGS:%=$(RPATH)/site-library/%)

#main package(s) and depends, suggests, imports that are in site-library
# (but note those in base)

DEPENDS_PKGS=TSfame tframe tframePlus TSdbi DBI fame tis zoo 
