#!/bin/sh

rm -f R-src/index.html

#In the event of a major upgrade of R (top level digit) R-3 needs to be 
# changed here and in Makevars.in.
# next creates index.html but could be -
(cd R-src ; wget -o Rver.log -O index.html "http://cran.at.r-project.org/src/base/R-3")
	
# omit time from date as wget of tar.gz has UTC time not local time
cat R-src/index.html | grep ".tar.gz" | tail -1 | perl \
   -pe 's/.*right">(\d{4})-(\w+)-(\d{2}) (\d{2}):(\d{2}).*/$1-$2-$3/go' >R-src/latestdt


cat R-src/index.html | grep ".tar.gz" | tail -1 | perl \
    -pe 's/.*R-(.*).tar.gz.*/R-$1/go' >R-src/latest

touch -m --date=`cat R-src/latestdt` R-src/index.html
touch -m --date=`cat R-src/latestdt` R-src/latest
touch -m --date=`cat R-src/latestdt` R-src/latestdt
