# these set dependencies in the default Makefile:
# $(SITE_PKGS:%=$(RPATH)/site-library/%)

#main package(s) and depends, suggests, imports that are in site-library
# (but note those in base)

SITE_PKGS=RPostgreSQL DBI 

SITEFRESH_PKGS=$(SITE_PKGS)
