#!/bin/sh

# script for retrieving packages' tests from CRAN and installing SelfTest. 

# THIS SCRIPT IS FOR DEVELOPMENT PURPOSES. NOT FOR GENERAL USE !!!

if [ $# -ne 0 ]; then 
   echo bad usage 
   exit 1
 fi

#ROBOHOME=/home/paul/RoboAdmin
#R=${ROBOHOME}/`cat $(ROBOHOME)/R-src/latest`/
R=/home/paul/RoboAdmin/R-3.0.1/

#REPOS="http://cran.r-project.org"
#echo $REPOS

PACS=`echo 'cat(rownames(available.packages(
 contriburl =contrib.url("http://cran.r-project.org", type="source")))[1201:1400])' \
  | ${R}/bin/R --slave  --vanilla`

#DONE TO ESG, ABOUT 1093 PACKAGES
# +[1094:1100]
# +[1101:1200]

# need fields = to get packages that do not work on current OS ??
#echo $PACS
#   available.packages(contriburl = contrib.url(getOption("repos"), type),
#                        method, fields = NULL,
#                        type = getOption("pkgType"),
#                        filters = NULL)
#"Package", "Version""OS_type""Repository"
#    repos = "http://cran.at.r-project.org")
#z <- available.packages()["$PACS"
# paste( z[1:2, "Package"],"_", z[1:2, "Version"],".tar.gz", sep="")

#  PKGsetup can be run in parallel, with substantial time savings 
#   downloading packages. PKGcommit cannot be run in parallel, or
#   the commits collide (on the working copy:  locked ...)

# NOT GOOD!  & JOBS START AND THEN SCRIPT MOVES ON BEFORE THEY FINISH

# RUN TWICE, COMMENTTING OUT ONE PART THEN OTHER !!!!!

#for f in $PACS 
#do
# nice -n 19  ./PKGsetup  $f &
#done

echo  Wait until jobs are all finished then comment above and uncomment below
echo  '  ps -elf | grep PKGsetup   '

for f in $PACS 
do
 ./PKGcommit  $f 
done
