#!/bin/sh

if [ $# -ne 2 ]; then 
   echo usage PKGsetup  packageName snippetName
   exit 1
 fi

svn propset svn:ignore "
Makefile   
Rplots*.pdf
Rplots*.ps"   $1/$2

svn commit $1/$2 -m "set package directory $1 properties to ignore some files."
