#!/bin/sh

if [ $# -ne 2 ]; then 
   echo usage SNIPsetup  packageName snippetName
   exit 1
 fi

#beware NO spaces on the end of lines in quotes
svn propset svn:ignore "
*.png
*.pdf
*.ps"   Packages/$1/$2

svn commit Packages/$1/$2 -m "set package directory $1 properties to ignore some files."
